"""Metadata provider boundary.

The default provider is Mock. Real downloader-backed providers are explicit
placeholders until external dependencies are introduced.
"""

from __future__ import annotations

from typing import Protocol
from urllib.parse import parse_qs, urlparse

from app.errors import ProviderNotImplementedError
from app.models import VideoMetadata, VideoSource


class MetadataProvider(Protocol):
    """Interface for resolving video metadata."""

    name: str

    def get_metadata(self, source: VideoSource) -> VideoMetadata:
        """Resolve metadata for a video source."""


class MockMetadataProvider:
    name = "mock"

    def get_metadata(self, source: VideoSource) -> VideoMetadata:
        return get_mock_metadata(source.raw_input, platform=source.platform)


class YtDlpMetadataProvider:
    name = "yt-dlp"

    def get_metadata(self, source: VideoSource) -> VideoMetadata:
        raise ProviderNotImplementedError(
            "yt-dlp metadata provider is not implemented yet. "
            "Stage 2 currently defines the provider boundary only."
        )


def get_mock_metadata(source_url: str, platform: str | None = None) -> VideoMetadata:
    """Return deterministic Mock metadata for a source URL."""

    parsed = urlparse(source_url)
    platform_name = platform or parsed.netloc or "local"
    source_id = _extract_source_id(parsed, platform_name)

    return VideoMetadata(
        title="Mock Video Knowledge Note",
        platform=platform_name,
        source_url=source_url,
        author="Mock Author",
        published_at="2026-07-05",
        duration="00:05:00",
        language="zh-CN",
        tags=["video2knowledge", "mock", "pkm"],
        status="mock",
        source_id=source_id,
        canonical_url=source_url,
        thumbnail_url="",
        description="Mock metadata generated by Video2Knowledge.",
        raw_metadata={"provider": "mock", "platform": platform_name},
    )


def get_metadata_for_source(source: VideoSource) -> VideoMetadata:
    """Resolve metadata through the current Mock provider boundary."""

    return get_metadata_with_provider(source, provider_name="mock")


def get_metadata_with_provider(
    source: VideoSource,
    provider_name: str = "mock",
) -> VideoMetadata:
    """Resolve metadata with an explicit provider name."""

    provider = build_metadata_provider(provider_name)
    return provider.get_metadata(source)


def build_metadata_provider(provider_name: str) -> MetadataProvider:
    """Create a metadata provider by name."""

    normalized = provider_name.lower()
    if normalized == "mock":
        return MockMetadataProvider()
    if normalized == "yt-dlp":
        return YtDlpMetadataProvider()
    raise ValueError(f"Unknown metadata provider: {provider_name}")


def _extract_source_id(parsed_url, platform: str) -> str:
    if platform == "youtube":
        query = parse_qs(parsed_url.query)
        if query.get("v"):
            return query["v"][0]
        if parsed_url.netloc.lower().endswith("youtu.be"):
            return parsed_url.path.strip("/")
    return ""
