"""Metadata provider boundary.

The default provider is Mock. Real downloader-backed providers are explicit
placeholders until external dependencies are introduced.
"""

from __future__ import annotations

from typing import Protocol
from urllib.parse import parse_qs, urlparse

from app.errors import MetadataProviderError
from app.models import VideoMetadata, VideoSource


class MetadataProvider(Protocol):
    """Interface for resolving video metadata."""

    name: str

    def get_metadata(self, source: VideoSource) -> VideoMetadata:
        """Resolve metadata for a video source."""


class MockMetadataProvider:
    name = "mock"

    def get_metadata(self, source: VideoSource) -> VideoMetadata:
        return get_mock_metadata(source.raw_input, platform=source.platform)


class YtDlpMetadataProvider:
    name = "yt-dlp"

    def get_metadata(self, source: VideoSource) -> VideoMetadata:
        if source.platform != "youtube":
            raise MetadataProviderError(
                "yt-dlp metadata provider currently supports YouTube only."
            )

        try:
            import yt_dlp
        except ImportError as error:
            raise MetadataProviderError(
                "yt-dlp is not installed. Install project dependencies before "
                "using metadata-provider yt-dlp."
            ) from error

        ydl_opts = {
            "skip_download": True,
            "quiet": True,
            "no_warnings": True,
            "noplaylist": True,
        }

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(source.raw_input, download=False)
                sanitized = ydl.sanitize_info(info)
        except Exception as error:
            raise MetadataProviderError(f"yt-dlp metadata extraction failed: {error}") from error

        if not isinstance(sanitized, dict):
            raise MetadataProviderError("yt-dlp returned metadata in an unexpected shape.")

        return _metadata_from_ytdlp_info(source, sanitized)


def get_mock_metadata(source_url: str, platform: str | None = None) -> VideoMetadata:
    """Return deterministic Mock metadata for a source URL."""

    parsed = urlparse(source_url)
    platform_name = platform or parsed.netloc or "local"
    source_id = _extract_source_id(parsed, platform_name)

    return VideoMetadata(
        title="Mock Video Knowledge Note",
        platform=platform_name,
        source_url=source_url,
        author="Mock Author",
        published_at="2026-07-05",
        duration="00:05:00",
        language="zh-CN",
        tags=["video2knowledge", "mock", "pkm"],
        status="mock",
        channel_id="",
        source_id=source_id,
        canonical_url=source_url,
        thumbnail_url="",
        description="Mock metadata generated by Video2Knowledge.",
        raw_metadata={"provider": "mock", "platform": platform_name},
    )


def get_metadata_for_source(source: VideoSource) -> VideoMetadata:
    """Resolve metadata through the current Mock provider boundary."""

    return get_metadata_with_provider(source, provider_name="mock")


def get_metadata_with_provider(
    source: VideoSource,
    provider_name: str = "mock",
) -> VideoMetadata:
    """Resolve metadata with an explicit provider name."""

    provider = build_metadata_provider(provider_name)
    return provider.get_metadata(source)


def build_metadata_provider(provider_name: str) -> MetadataProvider:
    """Create a metadata provider by name."""

    normalized = provider_name.lower()
    if normalized == "mock":
        return MockMetadataProvider()
    if normalized == "yt-dlp":
        return YtDlpMetadataProvider()
    raise ValueError(f"Unknown metadata provider: {provider_name}")


def _extract_source_id(parsed_url, platform: str) -> str:
    if platform == "youtube":
        query = parse_qs(parsed_url.query)
        if query.get("v"):
            return query["v"][0]
        if parsed_url.netloc.lower().endswith("youtu.be"):
            return parsed_url.path.strip("/")
    return ""


def _metadata_from_ytdlp_info(
    source: VideoSource,
    info: dict[str, object],
) -> VideoMetadata:
    title = _string_value(info.get("title"))
    source_id = _string_value(info.get("id"))
    canonical_url = _string_value(info.get("webpage_url")) or source.raw_input

    missing = [
        field_name
        for field_name, value in {
            "title": title,
            "source_id": source_id,
            "canonical_url": canonical_url,
        }.items()
        if not value
    ]
    if missing:
        raise MetadataProviderError(
            "yt-dlp metadata is missing required field(s): " + ", ".join(missing)
        )

    yt_tags = info.get("tags")
    tags = ["youtube", "metadata"]
    if isinstance(yt_tags, list):
        tags.extend(str(tag) for tag in yt_tags if isinstance(tag, str) and tag)

    return VideoMetadata(
        title=title,
        platform="youtube",
        source_url=source.raw_input,
        author=_string_value(info.get("uploader")) or _string_value(info.get("channel")),
        published_at=_format_upload_date(_string_value(info.get("upload_date"))),
        duration=_format_duration(info.get("duration")),
        language=_string_value(info.get("language")),
        tags=tags,
        status="metadata_only",
        channel_id=_string_value(info.get("channel_id"))
        or _string_value(info.get("uploader_id")),
        source_id=source_id,
        canonical_url=canonical_url,
        thumbnail_url=_string_value(info.get("thumbnail")),
        description=_string_value(info.get("description")),
        raw_metadata=info,
    )


def _string_value(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return str(value)


def _format_upload_date(value: str) -> str:
    if len(value) == 8 and value.isdigit():
        return f"{value[:4]}-{value[4:6]}-{value[6:8]}"
    return value


def _format_duration(value: object) -> str:
    if value is None:
        return ""
    try:
        total_seconds = int(float(str(value)))
    except ValueError:
        return str(value)

    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"
